graph TD
n0["bsharp_syntax::root::compilation_unit::CompilationUnit (bsharp_syntax::root::compilation_unit::CompilationUnit)"]
n1["bsharp_syntax::declarations::class_declaration::ClassDeclaration (bsharp_syntax::declarations::class_declaration::ClassDeclaration)"]
n2["bsharp_syntax::declarations::modifier::Modifier (bsharp_syntax::declarations::modifier::Modifier)"]
n3["bsharp_syntax::identifier::Identifier (bsharp_syntax::identifier::Identifier)"]
n4["bsharp_syntax::declarations::class_body_declaration::ClassBodyDeclaration (bsharp_syntax::declarations::class_body_declaration::ClassBodyDeclaration)"]
n5["bsharp_syntax::declarations::method_declaration::MethodDeclaration (bsharp_syntax::declarations::method_declaration::MethodDeclaration)"]
n6["bsharp_syntax::declarations::modifier::Modifier (bsharp_syntax::declarations::modifier::Modifier)"]
n7["bsharp_syntax::types::type_::Type (bsharp_syntax::types::type_::Type)"]
n8["bsharp_syntax::identifier::Identifier (bsharp_syntax::identifier::Identifier)"]
n9["bsharp_syntax::statements::statement::Statement (bsharp_syntax::statements::statement::Statement)"]
n10["bsharp_syntax::statements::statement::Statement (bsharp_syntax::statements::statement::Statement)"]
n11["bsharp_syntax::expressions::expression::Expression (bsharp_syntax::expressions::expression::Expression)"]
n12["bsharp_syntax::expressions::invocation_expression::InvocationExpression (bsharp_syntax::expressions::invocation_expression::InvocationExpression)"]
n13["bsharp_syntax::expressions::expression::Expression (bsharp_syntax::expressions::expression::Expression)"]
n14["bsharp_syntax::expressions::invocation_expression::Argument (bsharp_syntax::expressions::invocation_expression::Argument)"]
n15["bsharp_syntax::expressions::expression::Expression (bsharp_syntax::expressions::expression::Expression)"]
n16["bsharp_syntax::expressions::literal::Literal (bsharp_syntax::expressions::literal::Literal)"]
n17["bsharp_syntax::expressions::member_access_expression::MemberAccessExpression (bsharp_syntax::expressions::member_access_expression::MemberAccessExpression)"]
n18["bsharp_syntax::expressions::expression::Expression (bsharp_syntax::expressions::expression::Expression)"]
n19["bsharp_syntax::identifier::Identifier (bsharp_syntax::identifier::Identifier)"]
n0 --> n1
n1 --> n2
n1 --> n3
n1 --> n4
n4 --> n5
n5 --> n6
n5 --> n7
n5 --> n8
n5 --> n9
n9 --> n10
n10 --> n11
n11 --> n12
n12 --> n13
n12 --> n14
n14 --> n15
n15 --> n16
n13 --> n17
n17 --> n18
n17 --> n17
n18 --> n19
