use crate::DiagnosticSeverity;
use crate::diagnostics::diagnostic_category::DiagnosticCategory;
use bsharp_diagnostics_macros::diagnostics;

// B# Diagnostic Error/Warning Codes
// Format: BSE[XXXXX] for errors, BSW[XXXXX] for warnings
diagnostics!(
    BSE01001 => { message: "Constructors cannot be declared async" },
    BSE01002 => { message: "Constructors cannot have an explicit return type" },
    BSE01003 => { message: "Constructors cannot be virtual or abstract" },
    BSE01004 => { message: "Constructor cannot be both static and instance" },
    BSE01005 => { message: "Constructor name must match the containing class name" },
    BSE01006 => { message: "Multiple constructors with the same signature" },
    BSE01007 => { message: "Invalid base constructor call" },
    BSE01008 => { message: "Circular constructor dependency detected" },
    BSE01009 => { message: "Constructors cannot override other constructors" },
    BSE01010 => { message: "Interfaces cannot contain constructors" },

    BSE02001 => { message: "Abstract methods cannot have a body" },
    BSE02002 => { message: "Non-abstract methods must have a body" },
    BSE02003 => { message: "Virtual methods cannot be declared in sealed classes" },
    BSE02004 => { message: "Override method signature does not match base method" },
    BSE02005 => { message: "Methods cannot be both virtual and static" },
    BSE02006 => { message: "Static methods cannot override other methods" },
    BSE02007 => { message: "No suitable method found to override" },
    BSE02008 => { message: "Interface methods cannot have a body" },
    BSE02009 => { message: "Async methods must return Task or Task<T>" },
    BSE02010 => { message: "Method parameter names must be unique" },

    BSE03001 => { message: "Type could not be found" },
    BSE03002 => { message: "Cannot create an instance of this type" },
    BSE03003 => { message: "Type argument does not match constraint" },
    BSE03004 => { message: "Generic constraints are not satisfied" },
    BSE03005 => { message: "Circular type dependency detected" },
    BSE03006 => { message: "Interfaces cannot inherit from classes" },
    BSE03007 => { message: "Classes cannot inherit from interfaces (use : instead)" },
    BSE03008 => { message: "Structs cannot inherit from other types" },
    BSE03009 => { message: "Inconsistent type visibility" },
    BSE03010 => { message: "Generic type parameter names must be unique" },
    BSE03011 => { message: "Duplicate symbol declared in the same scope" },
    BSE03012 => { message: "Name could not be resolved or is ambiguous" },

    BSE04001 => { message: "Member is not accessible in this context" },
    BSE04002 => { message: "Interface members cannot be private" },
    BSE04003 => { message: "Struct members cannot be protected" },
    BSE04004 => { message: "Inconsistent accessibility between types" },
    BSE04005 => { message: "Static constructors cannot have access modifiers" },
    BSE04006 => { message: "Abstract members cannot be private" },
    BSE04007 => { message: "Virtual members cannot be private" },
    BSE04008 => { message: "Override member visibility does not match base" },
    BSE04009 => { message: "Sealed modifier can only be used on overriding members" },
    BSE04010 => { message: "Abstract members cannot exist in non-abstract classes" },

    BSW01001 => { message: "Method has high cyclomatic complexity" },
    BSW01002 => { message: "Method is too long" },
    BSW01003 => { message: "Method has too many parameters" },
    BSW01004 => { message: "Missing XML documentation" },
    BSW01005 => { message: "Deep nesting detected" },
    BSW01006 => { message: "Class is too large" },
    BSW01007 => { message: "High coupling detected" },
    BSW01008 => { message: "Low cohesion detected" },
    BSW01009 => { message: "God class anti-pattern detected" },
    BSW01010 => { message: "Feature envy anti-pattern detected" },

    BSW02001 => { message: "Naming convention violation" },
    BSW02002 => { message: "PascalCase naming expected" },
    BSW02003 => { message: "camelCase naming expected" },
    BSW02004 => { message: "UPPER_CASE naming expected" },
    BSW02005 => { message: "Variable is declared but never used" },
    BSW02006 => { message: "Parameter is declared but never used" },
    BSW02007 => { message: "Redundant assignment detected" },
    BSW02008 => { message: "Magic number should be a named constant" },
    BSW02009 => { message: "String literal duplication" },
    BSW02010 => { message: "Empty block statement" },

    BSW03001 => { message: "Boxing/unboxing operation detected" },
    BSW03002 => { message: "String concatenation in loop" },
    BSW03003 => { message: "LINQ performance concern" },
    BSW03004 => { message: "Unnecessary object allocation" },
    BSW03005 => { message: "Synchronous call in async method" },
    BSW03006 => { message: "Using exceptions for control flow" },
    BSW03007 => { message: "Inefficient collection usage" },
    BSW03008 => { message: "Closure allocation in loop" },
    BSW03009 => { message: "Large object heap allocation" },
    BSW03010 => { message: "Database query in loop" },

    BSW04001 => { message: "Potential SQL injection vulnerability" },
    BSW04002 => { message: "Potential XSS vulnerability" },
    BSW04003 => { message: "Hardcoded credential detected" },
    BSW04004 => { message: "Weak cryptographic algorithm" },
    BSW04005 => { message: "Potential path traversal vulnerability" },
    BSW04006 => { message: "Insecure random number generation" },
    BSW04007 => { message: "Missing input validation" },
    BSW04008 => { message: "Sensitive data in log statement" },
    BSW04009 => { message: "Unsafe deserialization" },
    BSW04010 => { message: "Missing authentication check" }
);
